import NextHead from "next/head";

type Props = {
  title: string;
};

export const Head = ({ title }: Props) => (
  <NextHead>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </NextHead>
);
